version: '3.8'

services:
  web:
    build: .
    container_name: web
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/home/hexedchild1/Kata/Repository/go-kata/course4Geoservice_1
    command: air main.go
  db:
    image: postgres:alpine
    container_name: geoservice
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5438:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: