// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/address/geocode": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves all possible Info based on given IP",
                "responses": {}
            }
        },
        "/api/address/search": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves all possible Info based on given Adress",
                "responses": {}
            }
        },
        "/api/login": {
            "get": {
                "summary": "Just Logging In",
                "responses": {}
            }
        },
        "/api/register": {
            "get": {
                "summary": "Registering new User!",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.0.0.0.0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "My First API",
	Description:      "'Cause today... is a day... of forgiveness! And to you... We can only say... A simple answer... Oh, hey, hey, hey!",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
